version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/scripts/python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ApprenticeGC"
    commit-message:
      prefix: "deps"
      include: "scope"

  # .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/dotnet"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ApprenticeGC"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "ApprenticeGC"
    commit-message:
      prefix: "deps"
      include: "scope"
