# GameConsole Deployment Configuration
# RFC-012-02: Deployment Pipeline Automation

# Environment-specific configuration for container deployment
environments:
  staging:
    replicas: 1
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "250m"
    healthCheck:
      enabled: true
      path: "/health"
      port: 8080
    scaling:
      enabled: false
    domain: "gameconsole.staging.example.com"
    
  production:
    replicas: 3
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    healthCheck:
      enabled: true
      path: "/health"
      port: 8080
    scaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPU: 70
    domain: "gameconsole.prod.example.com"

# Container configuration
container:
  port: 8080
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    
# Deployment strategy
deployment:
  strategy: "RollingUpdate"
  maxSurge: 1
  maxUnavailable: 0
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3

# Service configuration  
service:
  type: "ClusterIP"
  port: 80
  targetPort: 8080

# Ingress configuration (if applicable)
ingress:
  enabled: false
  tls: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"