name: agent-watchdog

on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]

jobs:
  restart_on_failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Derive PR, branch, and issue for failed run
        id: derive
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          set -euo pipefail
          # Fetch run to get branch
          RUN_JSON=$(gh api repos/$REPO/actions/runs/$RUN_ID)
          BRANCH=$(echo "$RUN_JSON" | jq -r '.head_branch')
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          # Try to resolve PR number by branch
          PR_NUM=$(gh pr list --repo "$REPO" --state open --head "$BRANCH" --json number --jq '.[0].number' || echo '')
          if [ -z "$PR_NUM" ]; then
            # maybe PR is already closed; pick latest PR on branch
            PR_NUM=$(gh pr list --repo "$REPO" --state all --head "$BRANCH" --json number,updatedAt --jq 'sort_by(.updatedAt)|last.number' || echo '')
          fi
          echo "pr_number=$PR_NUM" >> $GITHUB_OUTPUT
          ISSUE_NUM=""
          if [ -n "$PR_NUM" ]; then
            PR_JSON=$(gh pr view "$PR_NUM" --repo "$REPO" --json body,title,headRefName)
            ISSUE_NUM=$(echo "$PR_JSON" | jq -r '.body + "\n" + .title' | grep -oiE 'close[sd]? #([0-9]+)|fixe?[sd]? #([0-9]+)|resolve[sd]? #([0-9]+)' | grep -oE '[0-9]+' | head -n1)
          fi
          echo "issue_number=$ISSUE_NUM" >> $GITHUB_OUTPUT

      - name: Cleanup and recreate issue
        if: steps.derive.outputs.pr_number != '' && steps.derive.outputs.issue_number != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.event.repository.name }}
          python scripts/python/production/cleanup_recreate_issue.py \
            --owner "$OWNER" \
            --repo "$REPO_NAME" \
            --run-id ${{ github.event.workflow_run.id }} \
            --pr-number ${{ steps.derive.outputs.pr_number }} \
            --branch ${{ steps.derive.outputs.branch }} \
            --issue-number ${{ steps.derive.outputs.issue_number }} \
            --title "Recreated from watchdog: $(date -u +%FT%TZ)" \
            --assign-mode bot

      - name: Add failure note when auto-derivation incomplete
        if: steps.derive.outputs.pr_number == '' || steps.derive.outputs.issue_number == ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Watchdog could not auto-derive PR/Issue from failed run. Manual retry required."
