# NOTE: Deprecated alias. Prefer using the
# `Assign Copilot to Issue` workflow (`assign-copilot-to-issue.yml`).
# This remains for compatibility with older runbooks.
name: assign-next-micro

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: Issue number (e.g., 5)
        required: true

permissions:
  contents: read
  issues: write

jobs:
  assign:
    environment: copilot
    runs-on: ubuntu-latest
    steps:
      - name: Select token (prefer AUTO_APPROVE_TOKEN)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTO_APPROVE_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN }}
        run: |
          if [ -n "${AUTO_APPROVE_TOKEN:-}" ]; then
            echo "GH_TOKEN=$AUTO_APPROVE_TOKEN" >> $GITHUB_ENV
            echo "Using AUTO_APPROVE_TOKEN"
          else
            echo "GH_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
            echo "Using GITHUB_TOKEN"
          fi
          if [ -z "${AUTO_APPROVE_TOKEN:-}" ]; then
            echo "ERROR: AUTO_APPROVE_TOKEN (PAT) is required for assignment. Configure it in repo or environment 'copilot'." >&2
            exit 1
          fi
      - name: Debug suggestedActors (who is assignable)
        env:
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          OWNER=${REPO%/*}; NAME=${REPO#*/}
          Q='query($owner:String!,$name:String!){ repository(owner:$owner,name:$name){ suggestedActors(capabilities:[CAN_BE_ASSIGNED],first:100){ nodes{ login __typename ... on Bot { id } ... on User { id } } } } }'
          echo "Querying suggestedActors for $REPO"
          gh api graphql -f query="$Q" -F owner="$OWNER" -F name="$NAME" --jq '.data.repository.suggestedActors.nodes' || true

      - name: Assign specific issue to Copilot via GraphQL (bot id)
        env:
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.inputs.issue_number }}
        run: |
          set -euo pipefail
          # Resolve issue node id
          IID=$(gh issue view "$ISSUE" --repo "$REPO" --json id --jq .id)
          # Resolve Copilot bot id from suggestedActors
          OWNER=${REPO%/*}; NAME=${REPO#*/}
          Q='query($owner:String!,$name:String!){ repository(owner:$owner,name:$name){ suggestedActors(capabilities:[CAN_BE_ASSIGNED],first:100){ nodes{ login __typename ... on Bot { id } } } } }'
          BOT=$(gh api graphql -f query="$Q" -F owner="$OWNER" -F name="$NAME" --jq '.data.repository.suggestedActors.nodes[] | select(."__typename"=="Bot" and (.login|ascii_downcase|test("copilot"))) | .id' | head -n1 || true)
          # If already assigned, skip
          CUR=$(gh issue view "$ISSUE" --repo "$REPO" --json assignees --jq '.assignees[].login' || true)
          if echo "$CUR" | grep -qi '^copilot$'; then echo "Already assigned"; exit 0; fi
          if [ -z "$BOT" ]; then
            echo "No Copilot bot in suggestedActors; attempting fallback via user(login:Copilot) then copilot-swe-agent"
            COPILOT_ID=$(gh api graphql -f query='query($login:String!){ user(login:$login){ id __typename } }' -F login='Copilot' --jq '.data.user.id' || true)
            if echo "$COPILOT_ID" | grep -q '{'; then COPILOT_ID=""; fi
            if [ -z "$COPILOT_ID" ]; then
              COPILOT_ID=$(gh api graphql -f query='query($login:String!){ user(login:$login){ id __typename } }' -F login='copilot-swe-agent' --jq '.data.user.id' || true)
              if echo "$COPILOT_ID" | grep -q '{'; then COPILOT_ID=""; fi
            fi
            if [ -n "$COPILOT_ID" ]; then BOT="$COPILOT_ID"; else echo "No Copilot id resolved"; exit 1; fi
          fi
          # Assign via addAssigneesToAssignable
          M='mutation($assignableId: ID!, $assigneeIds: [ID!]!){ addAssigneesToAssignable(input:{ assignableId:$assignableId, assigneeIds:$assigneeIds }){ clientMutationId } }'
          gh api graphql -f query="$M" -F assignableId="$IID" -F assigneeIds="$BOT" >/dev/null
          gh issue view "$ISSUE" --repo "$REPO" --json assignees,url

