name: auto-approve-workflows

# This workflow automatically approves pending workflow runs from Copilot
on:
  schedule:
    # Run every 2 minutes to check for pending workflows
    - cron: '*/2 * * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: read
  pull-requests: read
  deployments: write

jobs:
  auto_approve_pending_workflows:
    runs-on: ubuntu-latest
    environment: copilot
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: main
      - name: Auto-approve or bypass blocked Copilot workflows
        env:
          # Expose both the default GITHUB_TOKEN and the PAT if available.
          # The script will use GITHUB_TOKEN for approvals and PAT for dispatching workflows.
          GH_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN || secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTO_APPROVE_PAT: ${{ secrets.AUTO_APPROVE_TOKEN }}
          REPO: ${{ github.repository }}
        run: python3 scripts/python/production/auto_approve_or_dispatch.py
