name: auto-ready-pr

on:
  # Gate on CI success for the PR to reduce false "ready" flips
  workflow_run:
    workflows: ["ci"]
    types: [completed]
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: read

jobs:
  mark_ready_on_ci_success:
    if: >-
      ${{
        github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'pull_request'
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Flip draft PR to ready when CI succeeded
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          # Take the first associated PR from the workflow_run payload
          PR_NUMBER=$(jq -r '.workflow_run.pull_requests[0].number' <<< "${{ toJson(github.event) }}")
          if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
            echo "No associated PR found"; exit 0; fi
          PR_JSON=$(gh pr view "$PR_NUMBER" --repo ${{ github.repository }} --json draft,title,author,headRepositoryOwner,baseRepository)
          DRAFT=$(jq -r .draft <<< "$PR_JSON")
          TITLE=$(jq -r .title <<< "$PR_JSON")
          AUTHOR=$(jq -r .author.login <<< "$PR_JSON")
          BASE=$(jq -r .baseRepository.nameWithOwner <<< "$PR_JSON")
          HEAD_OWNER=$(jq -r .headRepositoryOwner.login <<< "$PR_JSON")
          if [ "$DRAFT" != "true" ]; then echo "Not draft"; exit 0; fi
          case "$AUTHOR" in Copilot|app/copilot-swe-agent) : ;; *) echo "Non-Copilot author"; exit 0;; esac
          if [[ "$TITLE" != *RFC-* ]]; then echo "No RFC tag in title"; exit 0; fi
          # Ensure same-repo (not a fork)
          if [ "$BASE" != "${{ github.repository }}" ]; then echo "Different base repo"; exit 0; fi
          gh api -X POST repos/${{ github.repository }}/pulls/$PR_NUMBER/ready_for_review

  mark_ready_on_command:
    if: >-
      ${{
        github.event_name == 'issue_comment' &&
        startsWith(github.event.comment.body, '/ready') &&
        (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR') &&
        github.event.issue.pull_request
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Flip draft PR to ready via /ready command
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          PR_NUMBER=${{ github.event.issue.number }}
          PR_JSON=$(gh pr view "$PR_NUMBER" --repo ${{ github.repository }} --json draft)
          DRAFT=$(jq -r .draft <<< "$PR_JSON")
          if [ "$DRAFT" = "true" ]; then
            gh api -X POST repos/${{ github.repository }}/pulls/$PR_NUMBER/ready_for_review
          else
            echo "PR already ready"
          fi
