name: auto-approve-merge

on:
  pull_request_target:
    types: [opened, ready_for_review, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  approve_and_automerge:
    environment: copilot
    if: >-
      ${{
        (github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name) &&
        (github.event.pull_request.user.login == 'Copilot' || github.event.pull_request.user.login == 'app/copilot-swe-agent') &&
        (startsWith(github.event.pull_request.title, 'RFC-') || contains(github.event.pull_request.title, 'RFC-'))
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR (best-effort)
        continue-on-error: true
        run: |
          set -euo pipefail
          # Prefer environment PAT if provided, else fall back to GITHUB_TOKEN
          GH_TOKEN="${{ secrets.AUTO_APPROVE_TOKEN }}"; export GH_TOKEN
          if [ -z "$GH_TOKEN" ]; then GH_TOKEN='${{ secrets.GITHUB_TOKEN }}'; export GH_TOKEN; fi
          if ! gh pr review ${{ github.event.pull_request.number }} --approve --repo ${{ github.repository }}; then
            echo "Approval failed (policy may block Actions approvals). Proceeding without failing the job."
          fi

      - name: Enable auto-merge (squash)
        run: |
          set -euo pipefail
          GH_TOKEN="${{ secrets.AUTO_APPROVE_TOKEN }}"; export GH_TOKEN
          if [ -z "$GH_TOKEN" ]; then GH_TOKEN='${{ secrets.GITHUB_TOKEN }}'; export GH_TOKEN; fi
          # Attempt to enable auto-merge; requires repo setting "Allow auto-merge"
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --repo ${{ github.repository }} || true
