name: auto-merge-monitor

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["ci", "ci-dispatch"]
    types: ["completed"]

permissions:
  pull-requests: write
  contents: read

jobs:
  ensure_automerge:
    uses: ./.github/workflows/reusable-pr-merge.yml
    secrets: inherit  # pragma: allowlist secret
    with:
      repo: ${{ github.repository }}
      pr_number: ${{ github.event.pull_request.number || github.event.workflow_run.pull_requests[0].number || "" }}
      event_json: ${{ toJson(github.event) }}

  run_diagnostic_workflow:
    needs: ensure_automerge
    if: ${{ contains(github.event.pull_request.title || github.event.workflow_run.head_branch || "", "RFC-099") }}
    runs-on: ubuntu-latest
    environment: copilot
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run diagnostic workflow analysis for RFC-099
        env:
          GH_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN || secrets.GITHUB_TOKEN }}  # pragma: allowlist secret
          AUTO_APPROVE_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN }}  # pragma: allowlist secret
          REPO: ${{ github.repository }}
        run: |
          export PYTHONPATH="scripts/python/production:$PYTHONPATH"
          python3 scripts/python/production/orchestrator_cli.py diagnose --repo "$REPO"
