name: auto-approve-workflows

# This workflow automatically approves pending workflow runs from Copilot
on:
  schedule:
    # Run every 2 minutes to check for pending workflows
    - cron: '*/2 * * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  auto_approve_pending_workflows:
    runs-on: ubuntu-latest
    environment: copilot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Auto-approve or bypass blocked Copilot workflows
        env:
          GH_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN || secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: python3 .github/scripts/auto_approve_or_dispatch.py
