name: auto-approve-merge

on:
  pull_request_target:
    types: [opened, ready_for_review, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  approve_and_automerge:
    if: >-
      ${{
        (github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name) &&
        (github.event.pull_request.user.login == 'Copilot' || github.event.pull_request.user.login == 'app/copilot-swe-agent') &&
        (startsWith(github.event.pull_request.title, 'RFC-') || contains(github.event.pull_request.title, 'RFC-'))
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve --repo ${{ github.repository }}

      - name: Enable auto-merge (squash)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Attempt to enable auto-merge; requires repo setting "Allow auto-merge"
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --repo ${{ github.repository }} || true
