name: ci-dispatch

on:
  workflow_dispatch:
    inputs:
      target_ref:
        description: 'Git ref (branch or SHA) to run CI against'
        required: true
        default: 'main'

permissions:
  contents: read
  statuses: write

jobs:
  dispatch:
    uses: ./.github/workflows/reusable-ci-dispatch.yml
    secrets: inherit  # pragma: allowlist secret
    with:
      target_ref: ${{ inputs.target_ref }}
