name: ci

on:
  pull_request:
    branches: ["**"]
  push:
    branches:
      - 'copilot/**'

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./dotnet

      - name: Build (warnings as errors)
        run: dotnet build ./dotnet -warnaserror --no-restore

      - name: Test
        run: dotnet test ./dotnet --no-build --verbosity normal
