name: ensure-closes-link

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read
  issues: read

jobs:
  ensure_link:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR body contains Closes #<issue>
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          OWNER=${REPO%/*}
          REPO_NAME=${REPO#*/}
          python3 scripts/python/production/ensure_closes_link.py \
            --owner "$OWNER" \
            --repo "$REPO_NAME" \
            --pr-number "$PR"
