name: generate-micro-issues

on:
  workflow_dispatch:
    inputs:
      rfc_path:
        description: 'Path to RFC file (e.g., docs/RFC/RFC-090-agent-flow-smoke-test.md)'
        required: false
      notion_page_id:
        description: 'Notion page ID to ingest (takes precedence over rfc_path)'
        required: false
      assign_mode:
        description: 'Assignee preference (bot|user|auto)'
        required: false
        default: 'bot'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Generate micro issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}  # pragma: allowlist secret
          REPO: ${{ github.repository }}
        shell: bash
        run: |
          set -euo pipefail
          OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          RFC_PATH="${{ github.event.inputs.rfc_path || '' }}"
          NOTION_PAGE_ID="${{ github.event.inputs.notion_page_id || '' }}"
          ASSIGN_MODE="${{ github.event.inputs.assign_mode }}"

          if [ -n "$NOTION_PAGE_ID" ]; then
            python scripts/python/production/generate_micro_issues_from_rfc.py \
              --notion-page-id "$NOTION_PAGE_ID" \
              --owner "$OWNER" \
              --repo "$REPO_NAME" \
              --assign-mode "$ASSIGN_MODE"
          elif [ -n "$RFC_PATH" ]; then
            python scripts/python/production/generate_micro_issues_from_rfc.py \
              --rfc-path "$RFC_PATH" \
              --owner "$OWNER" \
              --repo "$REPO_NAME" \
              --assign-mode "$ASSIGN_MODE"
          else
            echo "::error::Provide either rfc_path, notion_page_id, or notion_collection input." >&2
            exit 1
          fi
