name: pr-flow-monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  actions: write
  deployments: write

jobs:
  monitor:
    environment: copilot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Monitor PR flow and self-heal
        env:
          GH_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN || secrets.GITHUB_TOKEN }}
          AUTO_APPROVE_PAT: ${{ secrets.AUTO_APPROVE_TOKEN }}
          REPO: ${{ github.repository }}
        run: python3 .github/scripts/monitor_pr_flow.py
