name: rfc-assign-cron

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  assign_earliest_unassigned:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve Copilot bot id
        id: bot
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          OWNER=${{ github.repository_owner }}
          NAME=${{ github.event.repository.name || github.event.workflow_run.repository.name || '' }}
          if [ -z "$NAME" ]; then NAME=$(basename "${{ github.repository }}"); fi
          Q='query($owner:String!,$name:String!){ repository(owner:$owner,name:$name){ suggestedActors(capabilities:[CAN_BE_ASSIGNED],first:100){ nodes{ login __typename ... on Bot { id } } } } }'
          BOT=$(gh api graphql -f query="$Q" -F owner="$OWNER" -F name="$NAME" --jq '.data.repository.suggestedActors.nodes[] | select(."__typename"=="Bot" and (.login|ascii_downcase|test("copilot"))) | .id' | head -n1)
          if [ -z "$BOT" ]; then echo "No Copilot bot id found"; exit 0; fi
          echo "id=$BOT" >> $GITHUB_OUTPUT
          echo "Resolved Copilot bot id: $BOT"

      - name: Select earliest unassigned micro per RFC
        id: select
        if: steps.bot.outputs.id != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          # Gather open issues that look like micro RFCs and pick the earliest unassigned per RFC
          IDS=$(gh issue list --repo "$REPO" --state open --json number,title,assignees \
            --jq '[ .[]
                    | select(.title | test("RFC-[0-9]{3}-[0-9]{2}"; "i"))
                    | {num:.number,
                       a:(.assignees|length),
                       r:(.title|capture("RFC-(?<r>[0-9]{3})-(?<m>[0-9]{2})").r|tonumber),
                       m:(.title|capture("RFC-(?<r>[0-9]{3})-(?<m>[0-9]{2})").m|tonumber)} ]
                  | sort_by(.r, .m, .num)
                  | group_by(.r)
                  | map( (map(select(.a==0)) | first) )
                  | map(select(. != null))
                  | map(.num)
                  | @sh')
          # Output space-separated list
          # shellcheck disable=SC2086
          echo "ids=$IDS" >> $GITHUB_OUTPUT
          echo "Selected issues: $IDS"

      - name: Assign selected issues to Copilot
        if: steps.select.outputs.ids != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BOT: ${{ steps.bot.outputs.id }}
        run: |
          set -euo pipefail
          # Parse the sh-encoded array from previous step
          eval "ARR=(${ { steps.select.outputs.ids } })" 2>/dev/null || eval "ARR=(${steps.select.outputs.ids})"
          M='mutation($assignableId: ID!, $actorIds: [ID!]!){ replaceActorsForAssignable(input:{ assignableId: $assignableId, actorIds: $actorIds }){ clientMutationId } }'
          for ISSUE in "${ARR[@]}"; do
            IID=$(gh issue view "$ISSUE" --repo "$REPO" --json id --jq .id)
            if [ -n "$IID" ]; then
              gh api graphql -f query="$M" -F assignableId="$IID" -F actorIds="$BOT" >/dev/null || true
              echo "Assigned #$ISSUE"
            fi
          done
