name: Secrets sweep (issues & PRs)

on:
  schedule:
    - cron: "0 3 * * *"   # daily at 3 AM UTC
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install TruffleHog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Scan repo + Issues + PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          trufflehog github \
            --repo="https://github.com/${{ github.repository }}" \
            --issue-comments --pr-comments \
            --results=verified,unknown \
            --json > trufflehog.json || true
          jq -e 'select(length>0)' trufflehog.json >/dev/null && exit 1 || exit 0

      - name: Upload findings
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-findings
          path: trufflehog.json

      - name: Create issue for findings
        if: failure()
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const findings = JSON.parse(fs.readFileSync('trufflehog.json', 'utf8'));
            const findingsCount = findings.length;

            const issueBody = `
            ## 🚨 Secret Detection Alert

            TruffleHog has detected **${findingsCount}** potential secret(s) in our repository.

            ### Action Required
            - Download the artifact from this workflow run to review findings
            - Rotate any confirmed secrets immediately
            - Update code/comments to remove exposed secrets
            - Consider adding patterns to .gitignore or pre-commit hooks

            ### Workflow Details
            - **Run ID**: ${{ github.run_id }}
            - **Scan Date**: ${new Date().toISOString()}
            - **Repository**: ${{ github.repository }}

            This issue was automatically created by the secrets-sweep workflow.
            `;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Secrets detected by TruffleHog scan - ${findingsCount} finding(s)`,
              body: issueBody,
              labels: ['security', 'urgent']
            });
