name: Update Project Status on Assignment

on:
  issues:
    types: [assigned, unassigned]

permissions:
  contents: read
  issues: read

jobs:
  update-project-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install -r scripts/python/requirements.txt

      - name: Update Project Item Status
        env:
          GITHUB_TOKEN: ${{ secrets.USE_PROJECT_V2_TOKEN }}
        run: |
          python scripts/python/production/update_project_status.py \
            --issue-number "${{ github.event.issue.number }}" \
            --action "${{ github.event.action }}" \
            --assignees ${{ join(github.event.issue.assignees.*.login, ' ') }}
